"""
STAAD.Pro text export — generates member load commands.

Output format matches STAAD.Pro syntax:
    LOAD <n> LOADTYPE <type> TITLE <title>
    MEMBER LOAD
    <member_id> UNI <dir> <f1> <d1> <d2>
    <member_id> TRAP <dir> <w1> <w2> <d1> <d2>

Both d1 and d2 are measured from the member start node.
"""

from __future__ import annotations
from collections import defaultdict
from app.models.schemas import OverlapResult, STAADFormat


def generate_staad_text(
    overlaps: list[OverlapResult],
    precision: int = 2,
    load_type_label: str = "Live",
) -> str:
    """
    Generate STAAD.Pro member load text from overlap results.

    Groups output by load case. Only includes affected members (loaded_length > 0).

    Format for UNI loads:
        member_id UNI direction intensity d1 d2

    Format for TRAP (trapezoidal) loads:
        member_id TRAP direction w1 w2 d1 d2

    Args:
        overlaps: List of computed overlap results
        precision: Decimal places for rounding values
        load_type_label: STAAD load type keyword (Live, Dead, Earth, etc.)

    Returns:
        STAAD.Pro formatted text string
    """
    if not overlaps:
        return "; No loads to export\n"

    # Group overlaps by load case
    by_case: dict[str, list[OverlapResult]] = defaultdict(list)
    for r in overlaps:
        if r.loaded_length > 0:
            by_case[r.load_case].append(r)

    if not by_case:
        return "; No affected members found\n"

    lines = []
    lines.append(f"; STAAD.Pro Member Load Export")
    lines.append(f"; Generated by Bridge Load Segmentation Tool")
    lines.append(f"; Precision: {precision} decimal places")
    lines.append("")

    # Map load cases to STAAD load numbers
    load_case_map = _build_load_case_map(by_case.keys())

    # Infer STAAD LOADTYPE from the load type of the overlaps
    load_type_keywords = {
        "PARTIAL_UDL": "Live",
        "PATCH_LOAD": "Live",
        "IRC_CLASS_AA": "Live",
        "IRC_70R": "Live",
        "IRC_CLASS_A": "Live",
        "SINGLE_AXLE_BOGIE": "Live",
        "DOUBLE_AXLE_BOGIE": "Live",
        "EARTH_PRESSURE": "None",
        "SURCHARGE": "None",
        "HYDROSTATIC": "None",
        "DEAD_LOAD": "Dead",
        "WEARING_COURSE": "Dead",
        "BRAKING": "Live",
        "CUSTOM": "None",
    }

    for case_id, results in by_case.items():
        load_num = load_case_map[case_id]

        # Determine load type from first result in case
        first_type = results[0].load_type.value if results else "CUSTOM"
        staad_type = load_type_keywords.get(first_type, "None")

        lines.append(f"LOAD {load_num} LOADTYPE {staad_type} TITLE {case_id}")
        lines.append("MEMBER LOAD")

        # Sort by member ID for clean output
        for r in sorted(results, key=lambda x: x.member_id):
            if r.staad_format == STAADFormat.TRAP and r.intensity_end is not None:
                # Trapezoidal: member TRAP dir w1 w2 d1 d2
                w1 = _fmt(r.intensity, precision)
                w2 = _fmt(r.intensity_end, precision)
                d1 = _fmt(r.front_distance, precision)
                d2 = _fmt(r.back_distance, precision)
                lines.append(
                    f"{r.member_id} TRAP {r.direction.value} {w1} {w2} {d1} {d2}"
                )
            else:
                # Uniform: member UNI dir f1 d1 d2
                f1 = _fmt(r.intensity, precision)
                d1 = _fmt(r.front_distance, precision)
                d2 = _fmt(r.back_distance, precision)
                lines.append(
                    f"{r.member_id} UNI {r.direction.value} {f1} {d1} {d2}"
                )

        lines.append("")

    return "\n".join(lines)


def generate_load_combinations(
    load_case_map: dict[str, int],
    combination_name: str = "Strength_I",
    factors: dict[str, float] | None = None,
) -> str:
    """
    Generate STAAD.Pro load combination commands.

    Default factors follow AASHTO LRFD Strength I.

    Args:
        load_case_map: Mapping of case IDs to STAAD load numbers
        combination_name: Name for the combination
        factors: Dict of case_id → load factor (default: all 1.0)

    Returns:
        STAAD.Pro LOAD COMB text
    """
    if not load_case_map:
        return ""

    if factors is None:
        factors = {k: 1.0 for k in load_case_map}

    comb_num = max(load_case_map.values()) + 100
    parts = []
    for case_id, load_num in sorted(load_case_map.items(), key=lambda x: x[1]):
        factor = factors.get(case_id, 1.0)
        parts.append(f"{load_num} {factor}")

    return f"LOAD COMB {comb_num} {combination_name}\n" + " ".join(parts) + "\n"


def _build_load_case_map(case_ids) -> dict[str, int]:
    """Map load case IDs to sequential STAAD load numbers starting at 1.

    Preserves the original insertion order so that LOAD numbers
    match the sequence in which the user added loads.
    """
    seen: dict[str, int] = {}
    for case_id in case_ids:
        if case_id not in seen:
            seen[case_id] = len(seen) + 1
    return seen


def _fmt(value: float, precision: int) -> str:
    """Format a number to the given precision."""
    return f"{value:.{precision}f}"
